version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./api:/srv/app
      - ./api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory 
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  pwa:
    build:
      context: ./pwa
      target: dev 
    volumes:
      - ./pwa:/srv/app

  caddy:
    volumes:
      - ./api/public:/srv/app/public:ro
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # This makes Traefik work
      SERVER_NAME: :80
    labels:
      traefik.enable: "true"
      traefik.http.routers.ap-caddy.entrypoints: https
      traefik.http.routers.ap-caddy.rule: Host(`${SERVER_NAME}`)
      traefik.http.routers.ap-caddy.tls: "true"
      traefik.http.services.ap-caddy.loadbalancer.server.port: 80
      traefik.docker.network: stonehenge-network
    networks:
      - stonehenge-network
      - default
      
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

networks:
  stonehenge-network:
    external: true
